import { BeforeAfterCase } from '@/types';

const cases: BeforeAfterCase[] = [
  {
    id: '1',
    slug: 'rhinoplastyka-ba-1',
    procedureSlug: 'rhinoplastyka-estetyczna',
    surgeonSlug: 'dr-aleksander-kowalski',
    clinicSlug: 'clinique-esthetique',
    title: 'Rhinoplastyka - korekta nosa garbatego',
    description: 'Pacjentka 28 lat, korekta nosa garbatego z asymetrią koniuszka.',
    beforeImage: {
      url: '/images/before-after/rhinoplastyka/before-1.jpg',
      alt: 'Przed rhinoplastyką',
      width: 800,
      height: 600,
    },
    afterImage: {
      url: '/images/before-after/rhinoplastyka/after-1.jpg',
      alt: 'Po rhinoplastyce',
      width: 800,
      height: 600,
    },
    patientAge: 28,
    patientGender: 'female',
    timeAfterProcedure: '3 miesiące po zabiegu',
    patientTestimonial: 'Wreszcie mogę spojrzeć w lustro bez kompleksów!',
    tags: ['rhinoplastyka', 'nos garbaty', 'kobieta'],
    featured: true,
  },
  {
    id: '2',
    slug: 'piersi-ba-1',
    procedureSlug: 'powiekszanie-piersi-implantami',
    surgeonSlug: 'dr-maria-wisniewska',
    clinicSlug: 'krakow-plastic-surgery-center',
    title: 'Powiększanie piersi implantami 320ml',
    description: 'Pacjentka 32 lata, powiększenie piersi okrągłymi implantami 320ml.',
    beforeImage: {
      url: '/images/before-after/piersi/before-1.jpg',
      alt: 'Przed powiększeniem piersi',
      width: 800,
      height: 600,
    },
    afterImage: {
      url: '/images/before-after/piersi/after-1.jpg',
      alt: 'Po powiększeniu piersi',
      width: 800,
      height: 600,
    },
    patientAge: 32,
    patientGender: 'female',
    timeAfterProcedure: '6 miesięcy po zabiegu',
    tags: ['piersi', 'implanty', 'kobieta'],
    featured: false,
  },
  {
    id: '3',
    slug: 'liposukcja-ba-1',
    procedureSlug: 'liposukcja-vaser',
    surgeonSlug: 'dr-piotr-nowak',
    clinicSlug: 'nova-aesthetica',
    title: 'Liposukcja VASER brzuch i boki',
    description: 'Pacjentka 35 lat, liposukcja brzucha i boków.',
    beforeImage: {
      url: '/images/before-after/liposukcja/before-1.jpg',
      alt: 'Przed liposukcją',
      width: 800,
      height: 600,
    },
    afterImage: {
      url: '/images/before-after/liposukcja/after-1.jpg',
      alt: 'Po liposukcji',
      width: 800,
      height: 600,
    },
    patientAge: 35,
    patientGender: 'female',
    timeAfterProcedure: '4 miesiące po zabiegu',
    tags: ['liposukcja', 'brzuch', 'kobieta'],
    featured: false,
  },
  {
    id: '4',
    slug: 'blefaroplastyka-ba-1',
    procedureSlug: 'blefaroplastyka-gorna',
    surgeonSlug: 'dr-anna-kaminska',
    clinicSlug: 'baltic-beauty-clinic',
    title: 'Blefaroplastyka górna',
    description: 'Pacjentka 52 lata, usunięcie nadmiaru skóry powiek górnych.',
    beforeImage: {
      url: '/images/before-after/blefaroplastyka/before-1.jpg',
      alt: 'Przed blefaroplastyką',
      width: 800,
      height: 600,
    },
    afterImage: {
      url: '/images/before-after/blefaroplastyka/after-1.jpg',
      alt: 'Po blefaroplastyce',
      width: 800,
      height: 600,
    },
    patientAge: 52,
    patientGender: 'female',
    timeAfterProcedure: '2 miesiące po zabiegu',
    tags: ['blefaroplastyka', 'powieki', 'kobieta'],
    featured: false,
  },
  {
    id: '5',
    slug: 'lifting-ba-1',
    procedureSlug: 'lifting-twarzy-deep-plane',
    surgeonSlug: 'dr-aleksander-kowalski',
    clinicSlug: 'clinique-esthetique',
    title: 'Lifting twarzy i szyi',
    description: 'Pacjentka 48 lat, pełen lifting twarzy i szyi metodą deep plane.',
    beforeImage: {
      url: '/images/before-after/lifting/before-1.jpg',
      alt: 'Przed liftingiem',
      width: 800,
      height: 600,
    },
    afterImage: {
      url: '/images/before-after/lifting/after-1.jpg',
      alt: 'Po liftingu',
      width: 800,
      height: 600,
    },
    patientAge: 48,
    patientGender: 'female',
    timeAfterProcedure: '6 miesięcy po zabiegu',
    patientTestimonial: 'Mój mąż mówi, że wyglądam na 35 lat!',
    tags: ['lifting', 'twarz', 'szyja', 'kobieta'],
    featured: true,
  },
  {
    id: '6',
    slug: 'abdominoplastyka-ba-1',
    procedureSlug: 'abdominoplastyka-pelna',
    surgeonSlug: 'dr-piotr-nowak',
    clinicSlug: 'nova-aesthetica',
    title: 'Abdominoplastyka z przemieszczeniem pępka',
    description: 'Pacjentka 38 lat, pełna abdominoplastyka po ciąży.',
    beforeImage: {
      url: '/images/before-after/abdominoplastyka/before-1.jpg',
      alt: 'Przed abdominoplastyką',
      width: 800,
      height: 600,
    },
    afterImage: {
      url: '/images/before-after/abdominoplastyka/after-1.jpg',
      alt: 'Po abdominoplastyce',
      width: 800,
      height: 600,
    },
    patientAge: 38,
    patientGender: 'female',
    timeAfterProcedure: '5 miesięcy po zabiegu',
    tags: ['abdominoplastyka', 'brzuch', 'kobieta'],
    featured: false,
  },
];

export function getMockBeforeAfterCases() {
  return cases;
}