import { Clinic } from '@/types';

const clinics: Clinic[] = [
  {
    id: '1',
    slug: 'clinique-esthetique',
    name: 'Clinique Esthétique',
    description: 'Luksusowa klinika chirurgii plastycznej w sercu Warszawy.',
    city: 'Warszawa',
    address: 'ul. Mokotowska 15/3, 00-640 Warszawa',
    phone: '+48 22 123 45 67',
    website: 'https://cliniqueesthetique.pl',
    logo: {
      url: '/images/clinics/clinique-logo.png',
      alt: 'Clinique Esthétique',
      width: 200,
      height: 80,
    },
    photos: [
      {
        url: '/images/clinics/clinique-1.jpg',
        alt: 'Clinique Estétique wnętrze',
        width: 1200,
        height: 800,
      },
    ],
    surgeonSlugs: ['dr-aleksander-kowalski'],
    procedureSlugs: ['rhinoplastyka-estetyczna', 'lifting-twarzy-deep-plane'],
    rating: 4.9,
    reviewCount: 156,
    certifications: ['ISO 9001', 'PTCHP'],
    priceLevel: 'luxury',
    features: ['Prywatna sala pooperacyjna', 'Hotel dla pacjentów'],
    financing: true,
    medicalTourism: true,
    languages: ['polski', 'angielski', 'niemiecki'],
    seo: {
      title: 'Clinique Esthétique — Klinika chirurgii plastycznej Warszawa',
      description: 'Luksusowa klinika chirurgii plastycznej w Warszawie.',
    },
  },
  {
    id: '2',
    slug: 'krakow-plastic-surgery-center',
    name: 'Kraków Plastic Surgery Center',
    description: 'Wiodący ośrodek chirurgii plastycznej w Małopolsce.',
    city: 'Kraków',
    address: 'ul. Floriańska 10, 31-021 Kraków',
    phone: '+48 12 345 67 89',
    website: 'https://krakowpsc.pl',
    logo: {
      url: '/images/clinics/krakow-logo.png',
      alt: 'Kraków PSC',
      width: 200,
      height: 80,
    },
    photos: [],
    surgeonSlugs: ['dr-maria-wisniewska'],
    procedureSlugs: ['powiekszanie-piersi-implantami', 'mastopeksja-klasyczna'],
    rating: 4.8,
    reviewCount: 98,
    certifications: ['PTCHP'],
    priceLevel: 'premium',
    features: ['Konsultacje online', 'Rehabilitacja'],
    financing: true,
    medicalTourism: true,
    languages: ['polski', 'angielski'],
    seo: {
      title: 'Kraków Plastic Surgery Center — Klinika chirurgii plastycznej Kraków',
      description: 'Wiodący ośrodek chirurgii plastycznej w Krakowie.',
    },
  },
  {
    id: '3',
    slug: 'nova-aesthetica',
    name: 'Nova Aesthetica',
    description: 'Nowoczesna klinika z akcentem na naturalne efekty.',
    city: 'Wrocław',
    address: 'ul. Krupnicza 5, 50-001 Wrocław',
    phone: '+48 71 345 67 89',
    website: 'https://novaaesthetica.pl',
    logo: {
      url: '/images/clinics/nova-logo.png',
      alt: 'Nova Aesthetica',
      width: 200,
      height: 80,
    },
    photos: [],
    surgeonSlugs: ['dr-piotr-nowak'],
    procedureSlugs: ['liposukcja-vaser', 'abdominoplastyka-pelna'],
    rating: 4.7,
    reviewCount: 72,
    certifications: ['PTCHP'],
    priceLevel: 'premium',
    features: ['Gabinet odnowy biologicznej'],
    financing: true,
    medicalTourism: false,
    languages: ['polski'],
    seo: {
      title: 'Nova Aesthetica — Klinika chirurgii plastycznej Wrocław',
      description: 'Nowoczesna klinika chirurgii plastycznej we Wrocławiu.',
    },
  },
  {
    id: '4',
    slug: 'baltic-beauty-clinic',
    name: 'Baltic Beauty Clinic',
    description: 'Klinika nad morzem, specjalizacja w zabiegach twarzy.',
    city: 'Gdańsk',
    address: 'ul. Długa 45, 80-001 Gdańsk',
    phone: '+48 58 345 67 89',
    website: 'https://balticbeautyclinic.pl',
    logo: {
      url: '/images/clinics/baltic-logo.png',
      alt: 'Baltic Beauty Clinic',
      width: 200,
      height: 80,
    },
    photos: [],
    surgeonSlugs: ['dr-anna-kaminska'],
    procedureSlugs: ['blefaroplastyka-gorna', 'lipofilling-twarzy'],
    rating: 4.6,
    reviewCount: 54,
    certifications: ['PTCHP'],
    priceLevel: 'mid',
    features: ['Hotel dla pacjentów'],
    financing: true,
    medicalTourism: true,
    languages: ['polski', 'angielski', 'szwedzki'],
    seo: {
      title: 'Baltic Beauty Clinic — Klinika chirurgii plastycznej Gdańsk',
      description: 'Klinika chirurgii plastycznej nad morzem.',
    },
  },
  {
    id: '5',
    slug: 'poznan-chirurgia',
    name: 'Poznań Chirurgia',
    description: 'Solidna klinika z długą tradycją.',
    city: 'Poznań',
    address: 'ul. Półwiejska 12, 60-001 Poznań',
    phone: '+48 61 234 56 78',
    website: 'https://poznan-chirurgia.pl',
    logo: {
      url: '/images/clinics/poznan-logo.png',
      alt: 'Poznań Chirurgia',
      width: 200,
      height: 80,
    },
    photos: [],
    surgeonSlugs: ['dr-tomasz-lewandowski'],
    procedureSlugs: ['otoplastyka', 'usuwanie-blizn'],
    rating: 4.5,
    reviewCount: 43,
    certifications: ['PTCHP'],
    priceLevel: 'mid',
    features: [],
    financing: false,
    medicalTourism: false,
    languages: ['polski'],
    seo: {
      title: 'Poznań Chirurgia — Klinika chirurgii plastycznej Poznań',
      description: 'Klinika chirurgii plastycznej w Poznaniu.',
    },
  },
  {
    id: '6',
    slug: 'lodz-aesthetic-institute',
    name: 'Łódź Aesthetic Institute',
    description: 'Instytut estetyki z zespołem doświadczonych specjalistów.',
    city: 'Łódź',
    address: 'ul. Piotrkowska 100, 90-001 Łódź',
    phone: '+48 42 234 56 78',
    website: 'https://lodzaesthetic.pl',
    logo: {
      url: '/images/clinics/lodz-logo.png',
      alt: 'Łódź Aesthetic Institute',
      width: 200,
      height: 80,
    },
    photos: [],
    surgeonSlugs: ['dr-katarzyna-zielinska'],
    procedureSlugs: ['labioplastyka', 'lipofilling-posladkow-bbl'],
    rating: 4.7,
    reviewCount: 61,
    certifications: ['PTCHP', 'ISO 9001'],
    priceLevel: 'premium',
    features: ['Konsultacje psychologiczne'],
    financing: true,
    medicalTourism: false,
    languages: ['polski', 'angielski'],
    seo: {
      title: 'Łódź Aesthetic Institute — Klinika chirurgii plastycznej Łódź',
      description: 'Instytut estetyki w Łodzi.',
    },
  },
];

export function getMockClinics() {
  return clinics;
}