import { Procedure } from '@/types';

const procedures: Procedure[] = [
  {
    id: '1',
    slug: 'rhinoplastyka-estetyczna',
    title: 'Rhinoplastyka estetyczna',
    excerpt: 'Korekta kształtu nosa dla harmonijnego wyglądu twarzy.',
    content: '',
    categorySlug: 'chirurgia-twarzy',
    subcategorySlug: 'rhinoplastyka',
    bodyArea: 'face',
    featuredImage: {
      url: '/images/procedures/rhinoplastyka.jpg',
      alt: 'Rhinoplastyka - korekta nosa',
      width: 800,
      height: 1000,
    },
    painLevel: 4,
    priceRange: { min: 8000, max: 25000 },
    recoveryTime: '2-3 tygodnie',
    anesthesiaType: 'general',
    resultDuration: 'trwałe',
    operationDuration: '1.5-3 godziny',
    hospitalization: '1 noc',
    satisfactionRate: 94,
    popularityScore: 98,
    contraindications: [
      'Aktywne infekcje górnych dróg oddechowych',
      'Nieuregulowana cukrzyca',
      'Zaburzenia krzepnięcia krwi',
    ],
    risks: [
      'Asymetria nosa',
      'Trudności w oddychaniu',
      'Przebarwienia skóry',
    ],
    benefits: [
      'Poprawa proporcji nosa do twarzy',
      'Zwiększenie pewności siebie',
      'Korekta problemów z oddychaniem',
      'Trwałe efekty',
    ],
    aftercareSteps: [
      { day: '1-3', instruction: 'Odpoczynek, unikanie wysiłku' },
      { day: '4-7', instruction: 'Zdjęcie opatrunku gipsowego' },
      { day: '2-3 tygodnie', instruction: 'Unikanie sportu i ciężkiej pracy' },
      { day: '6 miesięcy', instruction: 'Ostateczny kształt nosa' },
    ],
    faq: [
      {
        question: 'Czy rhinoplastyka jest bolesna?',
        answer: 'Sam zabieg jest wykonywany pod narkozą, więc nie odczuwasz bólu. Po operacji możesz odczuwać dyskomfort i obrzęk, który ustępuje w ciągu 1-2 tygodni.',
      },
      {
        question: 'Jak długo trzeba nosić opatunek?',
        answer: 'Opatrunek gipsowy nosi się około 7-10 dni. Przez kilka pierwszych dni mogą być również wkładane tampony do nosa.',
      },
      {
        question: 'Kiedy widoczny jest efekt końcowy?',
        answer: 'Ostateczny kształt nosa kształtuje się przez około 6 miesięcy do roku po zabiegu, choć podstawowy efekt widoczny jest po zdjęciu gipsu.',
      },
      {
        question: 'Czy można oddychać normalnie po zabiegu?',
        answer: 'Przez pierwsze dni może być utrudnione oddychanie przez nos z powodu obrzęku. Zazwyczaj po 2-3 tygodniach oddychanie wraca do normy.',
      },
    ],
    relatedProcedures: ['blefaroplastyka-gorna', 'lifting-twarzy-deep-plane', 'lipofilling-twarzy'],
    seo: {
      title: 'Rhinoplastyka estetyczna — cena, przebieg, efekty',
      description: 'Rhinoplastyka estetyczna - korekta nosa. Sprawdź cenę, przebieg zabiegu, czas rekonwalescencji i efekty.',
    },
    updatedAt: '2026-01-15',
  },
  {
    id: '2',
    slug: 'blefaroplastyka-gorna',
    title: 'Blefaroplastyka górna',
    excerpt: 'Usunięcie nadmiaru skóry i tłuszczu z powiek górnych.',
    content: '',
    categorySlug: 'chirurgia-twarzy',
    subcategorySlug: 'blefaroplastyka',
    bodyArea: 'face',
    featuredImage: {
      url: '/images/procedures/blefaroplastyka.jpg',
      alt: 'Blefaroplastyka - korekta powiek',
      width: 800,
      height: 1000,
    },
    painLevel: 2,
    priceRange: { min: 4000, max: 8000 },
    recoveryTime: '10-14 dni',
    anesthesiaType: 'local',
    resultDuration: '5-10 lat',
    operationDuration: '45-90 minut',
    hospitalization: 'wychód tego samego dnia',
    satisfactionRate: 96,
    popularityScore: 88,
    contraindications: [
      'Zespół suchego oka',
      'Aktywne choroby oczu',
      'Nieuregulowane ciśnienie krwi',
    ],
    risks: [
      'Przejściowe problemy z zamykaniem oka',
      'Asymetria powiek',
      'Infekcja rany',
    ],
    benefits: [
      'Młodszy, wypoczęty wygląd',
      'Poprawa поля widzenia',
      'Krótki czas rekonwalescencji',
      'Subtelne, naturalne efekty',
    ],
    aftercareSteps: [
      { day: '1-3', instruction: 'Zimne kompresy, unikanie wysiłku' },
      { day: '5-7', instruction: 'Zdjęcie szwów' },
      { day: '2 tygodnie', instruction: 'Powrót do normalnej aktywności' },
      { day: '4-6 tygodni', instruction: 'Unikanie basenu i sauny' },
    ],
    faq: [
      {
        question: 'Czy blefaroplastyka zostawia widoczne blizny?',
        answer: 'Blizny są ukryte w naturalnym załamaniu powieki i po pełnym wygojeniu są prawie niewidoczne.',
      },
      {
        question: 'Jak długo utrzymuje się efekt?',
        answer: 'Efekt blefaroplastyki górnej utrzymuje się zazwyczaj 5-10 lat, w zależności od indywidualnych czynników.',
      },
      {
        question: 'Czy można wrócić do pracy po zabiegu?',
        answer: 'Większość pacjentów wraca do pracy biurowej po 7-10 dniach. Zaleca się unikanie wysiłku fizycznego przez 2-3 tygodnie.',
      },
    ],
    relatedProcedures: ['rhinoplastyka-estetyczna', 'lifting-twarzy-deep-plane'],
    seo: {
      title: 'Blefaroplastyka górna — cena, przebieg, efekty',
      description: 'Blefaroplastyka powiek górnych - usunięcie opadającej skóry powiek. Sprawdź cenę i efekty zabiegu.',
    },
    updatedAt: '2026-01-10',
  },
  {
    id: '3',
    slug: 'lifting-twarzy-deep-plane',
    title: 'Lifting twarzy deep plane',
    excerpt: 'Najbardziej zaawansowana technika liftingu twarzy dla naturalnych rezultatów.',
    content: '',
    categorySlug: 'chirurgia-twarzy',
    subcategorySlug: 'lifting-twarzy',
    bodyArea: 'face',
    featuredImage: {
      url: '/images/procedures/lifting-deep-plane.jpg',
      alt: 'Lifting twarzy metodą deep plane',
      width: 800,
      height: 1000,
    },
    painLevel: 5,
    priceRange: { min: 25000, max: 55000 },
    recoveryTime: '3-4 tygodnie',
    anesthesiaType: 'general',
    resultDuration: '10-15 lat',
    operationDuration: '4-6 godzin',
    hospitalization: '1-2 noce',
    satisfactionRate: 97,
    popularityScore: 85,
    contraindications: [
      'Aktywne infekcje',
      'Ciężkie choroby serca',
      'Zaburzenia krzepnięcia',
    ],
    risks: [
      'Uszkodzenie nerwu twarzowego',
      'Asymetria',
      'Przebarwienia skóry',
    ],
    benefits: [
      'Najbardziej naturalny efekt liftingu',
      'Długotrwałe rezultaty',
      'Poprawa konturu twarzy i szyi',
      'Minimalne napięcie skóry',
    ],
    aftercareSteps: [
      { day: '1-2', instruction: 'Odpoczynek w pozycji półsiedzącej' },
      { day: '3-5', instruction: 'Zdjęcie drenażów' },
      { day: '2-3 tygodnie', instruction: 'Zdjęcie szwów' },
      { day: '6-8 tygodni', instruction: 'Powrót do pełnej aktywności' },
    ],
    faq: [
      {
        question: 'Czym lifting deep plane różni się od tradycyjnego liftingu?',
        answer: 'Technika deep plane operuje na głębszych warstwach tkanek, co pozwala na przemieszczenie tkanek bez napięcia skóry, dając bardziej naturalne i długotrwałe efekty.',
      },
      {
        question: 'Jak długo trwa rekonwalescencja?',
        answer: 'Podstawowy powrót do formy to 3-4 tygodnie. Obrzęk i zasinienia ustępują stopniowo, a ostateczny efekt widoczny jest po 3-6 miesiącach.',
      },
      {
        question: 'Czy efekt liftingu jest trwały?',
        answer: 'Tak, efekty liftingu deep plane utrzymują się 10-15 lat. Proces starzenia nadal postępuje, ale będziesz wyglądać zawsze młodziej niż bez zabiegu.',
      },
    ],
    relatedProcedures: ['blefaroplastyka-gorna', 'rhinoplastyka-estetyczna'],
    seo: {
      title: 'Lifting twarzy deep plane — cena, przebieg, efekty',
      description: 'Lifting twarzy metodą deep plane - najnowocześniejsza technika odmładzania twarzy. Sprawdź cenę i efekty.',
    },
    updatedAt: '2026-01-12',
  },
  {
    id: '4',
    slug: 'otoplastyka',
    title: 'Otoplastyka',
    excerpt: 'Korekta odstających uszu dla harmonijnego wyglądu.',
    content: '',
    categorySlug: 'chirurgia-twarzy',
    subcategorySlug: 'otoplastyka',
    bodyArea: 'face',
    featuredImage: {
      url: '/images/procedures/otoplastyka.jpg',
      alt: 'Otoplastyka - korekta uszu',
      width: 800,
      height: 1000,
    },
    painLevel: 3,
    priceRange: { min: 5000, max: 12000 },
    recoveryTime: '2-3 tygodnie',
    anesthesiaType: 'local',
    resultDuration: 'trwałe',
    operationDuration: '1-2 godziny',
    hospitalization: 'wychód tego samego dnia',
    satisfactionRate: 95,
    popularityScore: 72,
    contraindications: [
      'Aktywne infekcje ucha',
      'Zaburzenia gojenia',
      'Nieuregulowana cukrzyca',
    ],
    risks: [
      'Asymetria uszu',
      'Przebarwienia skóry',
      'Infekcja rany',
    ],
    benefits: [
      'Trwała korekta odstających uszu',
      'Poprawa pewności siebie',
      'Minimalne blizny',
      'Szybka rekonwalescencja',
    ],
    aftercareSteps: [
      { day: '1-3', instruction: 'Noszenie opaski uciskowej' },
      { day: '7-10', instruction: 'Zdjęcie szwów' },
      { day: '2-3 tygodnie', instruction: 'Unikanie sportu' },
      { day: '6 tygodni', instruction: 'Spanie na plecach' },
    ],
    faq: [
      {
        question: 'Czy otoplastyka jest bolesna?',
        answer: 'Zabieg wykonywany jest w znieczuleniu miejscowym, więc nie odczuwasz bólu. Po zabiegu może wystąpić przejściowy dyskomfort.',
      },
      {
        question: 'Kiedy można wrócić do pracy?',
        answer: 'Do pracy biurowej można wrócić po 3-5 dniach. Praca fizyczna wymaga 2-3 tygodni przerwy.',
      },
      {
        question: 'Czy efekt jest trwały?',
        answer: 'Tak, efekt otoplastyki jest trwały. Raz skorygowane uszy zachowują swój kształt na stałe.',
      },
    ],
    relatedProcedures: [],
    seo: {
      title: 'Otoplastyka — cena, przebieg, efekty',
      description: 'Otoplastyka - korekta odstających uszu. Sprawdź cenę, przebieg zabiegu i efekty.',
    },
    updatedAt: '2026-01-08',
  },
  {
    id: '5',
    slug: 'powiekszanie-piersi-implantami',
    title: 'Powiększanie piersi implantami',
    excerpt: 'Augmentacja piersi z użyciem implantów dla pełniejszego kształtu.',
    content: '',
    categorySlug: 'chirurgia-piersi',
    subcategorySlug: 'powiekszanie-piersi',
    bodyArea: 'breast',
    featuredImage: {
      url: '/images/procedures/powiekszanie-piersi.jpg',
      alt: 'Powiększanie piersi implantami',
      width: 800,
      height: 1000,
    },
    painLevel: 5,
    priceRange: { min: 12000, max: 35000 },
    recoveryTime: '4-6 tygodni',
    anesthesiaType: 'general',
    resultDuration: 'trwałe (wymiana co 10-15 lat)',
    operationDuration: '1.5-2.5 godziny',
    hospitalization: '1 noc',
    satisfactionRate: 93,
    popularityScore: 95,
    contraindications: [
      'Ciąża i karmienie piersią',
      'Aktywne infekcje',
      'Choroby autoimmunologiczne',
    ],
    risks: [
      'Kapsuła tkankowa wokół implantu',
      'Asymetria piersi',
      'Przemieszczenie implantu',
    ],
    benefits: [
      'Trwałe powiększenie piersi',
      'Poprawa proporcji sylwetki',
      'Zwiększenie pewności siebie',
      'Naturalny wygląd przy dobrej technice',
    ],
    aftercareSteps: [
      { day: '1-2', instruction: 'Odpoczynek, noszenie specjalnego stanika' },
      { day: '7-14', instruction: 'Wizyta kontrolna, usunięcie szwów' },
      { day: '4-6 tygodni', instruction: 'Unikanie sportu i ciężkiego wysiłku' },
    ],
    faq: [
      {
        question: 'Jak długo utrzymują się implanty piersi?',
        answer: 'Współczesne implanty są bardzo trwałe, ale producenci zalecają ich wymianę co 10-15 lat.',
      },
      {
        question: 'Czy można karmić piersią po zabiegu?',
        answer: 'Tak, przy odpowiedniej technice chirurgicznej możliwe jest karmienie piersią po powiększeniu.',
      },
      {
        question: 'Jaki jest okres rekonwalescencji?',
        answer: 'Powrót do pracy biurowej to 1-2 tygodnie. Pełna aktywność fizyczna po 4-6 tygodniach.',
      },
    ],
    relatedProcedures: ['mastopeksja-klasyczna'],
    seo: {
      title: 'Powiększanie piersi implantami — cena, przebieg, efekty',
      description: 'Augmentacja piersi implantami - cena, przebieg zabiegu, okres rekonwalescencji i efekty.',
    },
    updatedAt: '2026-01-14',
  },
  {
    id: '6',
    slug: 'mastopeksja-klasyczna',
    title: 'Mastopeksja klasyczna',
    excerpt: 'Podniesienie i modelowanie opadających piersi.',
    content: '',
    categorySlug: 'chirurgia-piersi',
    subcategorySlug: 'mastopeksja',
    bodyArea: 'breast',
    featuredImage: {
      url: '/images/procedures/mastopeksja.jpg',
      alt: 'Mastopeksja - podniesienie piersi',
      width: 800,
      height: 1000,
    },
    painLevel: 4,
    priceRange: { min: 10000, max: 22000 },
    recoveryTime: '4-6 tygodni',
    anesthesiaType: 'general',
    resultDuration: '5-10 lat',
    operationDuration: '2-3 godziny',
    hospitalization: '1-2 noce',
    satisfactionRate: 91,
    popularityScore: 78,
    contraindications: [
      'Planowana ciąża',
      'Aktywne infekcje',
      'Zaburzenia krzepnięcia',
    ],
    risks: [
      'Asymetria piersi',
      'Zmniejszenie czucia brodawek',
      'Widoczne blizny',
    ],
    benefits: [
      'Uniesienie opadających piersi',
      'Poprawa kształtu i jędrności',
      'Krótkotrwała poprawa sylwetki',
    ],
    aftercareSteps: [
      { day: '1-3', instruction: 'Noszenie stanika uciskowego' },
      { day: '10-14', instruction: 'Zdjęcie szwów' },
      { day: '4-6 tygodni', instruction: 'Unikanie sportu' },
    ],
    faq: [
      {
        question: 'Czy mastopeksja pozostawia blizny?',
        answer: 'Tak, blizny są wokół otoczki brodawki i pionowo w dół oraz w fałdzie podpiersiowym. Z czasem stają się mało widoczne.',
      },
      {
        question: 'Jak długo utrzymuje się efekt?',
        answer: 'Efekt podniesienia piersi utrzymuje się 5-10 lat, ale może ulec zmianie w wyniku starzenia, wahań wagi i ciąży.',
      },
    ],
    relatedProcedures: ['powiekszanie-piersi-implantami'],
    seo: {
      title: 'Mastopeksja — cena, przebieg, efekty',
      description: 'Podniesienie piersi mastopeksja - cena, przebieg zabiegu, efekty.',
    },
    updatedAt: '2026-01-11',
  },
  {
    id: '7',
    slug: 'liposukcja-vaser',
    title: 'Liposukcja VASER',
    excerpt: 'Zaawansowana liposukcja z wykorzystaniem technologii ultradźwiękowej.',
    content: '',
    categorySlug: 'plastyka-brzucha',
    subcategorySlug: 'liposukcja',
    bodyArea: 'body',
    featuredImage: {
      url: '/images/procedures/liposukcja-vaser.jpg',
      alt: 'Liposukcja VASER',
      width: 800,
      height: 1000,
    },
    painLevel: 4,
    priceRange: { min: 6000, max: 20000 },
    recoveryTime: '2-4 tygodnie',
    anesthesiaType: 'sedation',
    resultDuration: 'trwałe przy utrzymaniu wagi',
    operationDuration: '2-4 godziny',
    hospitalization: 'wychód tego samego dnia lub 1 noc',
    satisfactionRate: 89,
    popularityScore: 92,
    contraindications: [
      'Otyłość znacznego stopnia',
      'Zaburzenia krzepnięcia',
      'Choroby serca',
    ],
    risks: [
      'Asymetria',
      'Nierówności skóry',
      'Przebarwienia skóry',
    ],
    benefits: [
      'Precyzyjne modelowanie sylwetki',
      'Krótszy czas rekonwalescencji niż tradycyjna liposukcja',
      'Lepsza retrakcja skóry',
    ],
    aftercareSteps: [
      { day: '1-3', instruction: 'Noszenie ubrania uciskowego' },
      { day: '7-14', instruction: 'Kontrola, możliwe usunięcie szwów' },
      { day: '4-6 tygodni', instruction: 'Unikanie intensywnego wysiłku' },
    ],
    faq: [
      {
        question: 'Czy liposukcja VASER jest bolesna?',
        answer: 'Zabieg wykonywany jest w sedacji, więc nie odczuwasz bólu. Po zabiegu może wystąpić dyskomfort i obrzęk, który ustępuje stopniowo.',
      },
      {
        question: 'Kiedy widoczny jest efekt?',
        answer: 'Początkowy efekt widoczny jest po ustąpieniu obrzęku, ale ostateczny rezultat kształtuje się przez 3-6 miesięcy.',
      },
    ],
    relatedProcedures: ['abdominoplastyka-pelna'],
    seo: {
      title: 'Liposukcja VASER — cena, przebieg, efekty',
      description: 'Liposukcja VASER - nowoczesna metoda odsysania tłuszczu. Sprawdź cenę i efekty.',
    },
    updatedAt: '2026-01-13',
  },
  {
    id: '8',
    slug: 'abdominoplastyka-pelna',
    title: 'Abdominoplastyka pełna',
    excerpt: 'Plastyka brzucha z usunięciem nadmiaru skóry i tłuszczu.',
    content: '',
    categorySlug: 'plastyka-brzucha',
    subcategorySlug: 'abdominoplastyka',
    bodyArea: 'body',
    featuredImage: {
      url: '/images/procedures/abdominoplastyka.jpg',
      alt: 'Abdominoplastyka pełna',
      width: 800,
      height: 1000,
    },
    painLevel: 6,
    priceRange: { min: 12000, max: 30000 },
    recoveryTime: '4-6 tygodni',
    anesthesiaType: 'general',
    resultDuration: 'trwałe',
    operationDuration: '3-5 godzin',
    hospitalization: '1-2 noce',
    satisfactionRate: 92,
    popularityScore: 87,
    contraindications: [
      'Planowane ciąże',
      'Znaczna otyłość',
      'Zaburzenia gojenia',
    ],
    risks: [
      'Seroma (nagromadzenie płynu)',
      'Asymetria',
      'Szerokie blizny',
    ],
    benefits: [
      'Płaski brzuch',
      'Usunięcie rozstępów',
      'Wzmocnienie mięśni brzucha',
    ],
    aftercareSteps: [
      { day: '1-3', instruction: 'Odpoczynek, noszenie pasa uciskowego' },
      { day: '10-14', instruction: 'Zdjęcie szwów' },
      { day: '6-8 tygodni', instruction: 'Unikanie wysiłku, zgięcia' },
    ],
    faq: [
      {
        question: 'Czy abdominoplastyka jest bolesna?',
        answer: 'To jeden z bardziej bolesnych zabiegów chirurgii plastycznej. Ból ustępuje stopniowo przez 2-3 tygodnie.',
      },
      {
        question: 'Jak długo trzeba nosić pas uciskowy?',
        answer: 'Pas uciskowy nosi się przez 6-8 tygodni, zdejmując go tylko do kąpieli.',
      },
    ],
    relatedProcedures: ['liposukcja-vaser'],
    seo: {
      title: 'Abdominoplastyka pełna — cena, przebieg, efekty',
      description: 'Plastyka brzucha abdominoplastyka - cena, przebieg zabiegu, efekty.',
    },
    updatedAt: '2026-01-09',
  },
];

export function getMockProcedures() {
  return procedures;
}

export function getMockProcedureBySlug(slug: string) {
  return procedures.find((p) => p.slug === slug) || null;
}